export interface CountryItem {
  value: string // ISO 2-letter code (e.g. 'US', 'ES', 'MX')
  label: string // Common name
  flag: string // Flag image URL
}

export const WORLD_COUNTRIES: CountryItem[] = [
  { value: 'AF', label: 'Afghanistan', flag: 'https://flagcdn.com/w40/af.png' },
  { value: 'AX', label: 'Åland Islands', flag: 'https://flagcdn.com/w40/ax.png' },
  { value: 'AL', label: 'Albania', flag: 'https://flagcdn.com/w40/al.png' },
  { value: 'DZ', label: 'Algeria', flag: 'https://flagcdn.com/w40/dz.png' },
  { value: 'AS', label: 'American Samoa', flag: 'https://flagcdn.com/w40/as.png' },
  { value: 'AD', label: 'Andorra', flag: 'https://flagcdn.com/w40/ad.png' },
  { value: 'AO', label: 'Angola', flag: 'https://flagcdn.com/w40/ao.png' },
  { value: 'AI', label: 'Anguilla', flag: 'https://flagcdn.com/w40/ai.png' },
  { value: 'AQ', label: 'Antarctica', flag: 'https://flagcdn.com/w40/aq.png' },
  { value: 'AG', label: 'Antigua & Barbuda', flag: 'https://flagcdn.com/w40/ag.png' },
  { value: 'AR', label: 'Argentina', flag: 'https://flagcdn.com/w40/ar.png' },
  { value: 'AM', label: 'Armenia', flag: 'https://flagcdn.com/w40/am.png' },
  { value: 'AW', label: 'Aruba', flag: 'https://flagcdn.com/w40/aw.png' },
  { value: 'AU', label: 'Australia', flag: 'https://flagcdn.com/w40/au.png' },
  { value: 'AT', label: 'Austria', flag: 'https://flagcdn.com/w40/at.png' },
  { value: 'AZ', label: 'Azerbaijan', flag: 'https://flagcdn.com/w40/az.png' },
  { value: 'BS', label: 'Bahamas', flag: 'https://flagcdn.com/w40/bs.png' },
  { value: 'BH', label: 'Bahrain', flag: 'https://flagcdn.com/w40/bh.png' },
  { value: 'BD', label: 'Bangladesh', flag: 'https://flagcdn.com/w40/bd.png' },
  { value: 'BB', label: 'Barbados', flag: 'https://flagcdn.com/w40/bb.png' },
  { value: 'BY', label: 'Belarus', flag: 'https://flagcdn.com/w40/by.png' },
  { value: 'BE', label: 'Belgium', flag: 'https://flagcdn.com/w40/be.png' },
  { value: 'BZ', label: 'Belize', flag: 'https://flagcdn.com/w40/bz.png' },
  { value: 'BJ', label: 'Benin', flag: 'https://flagcdn.com/w40/bj.png' },
  { value: 'BM', label: 'Bermuda', flag: 'https://flagcdn.com/w40/bm.png' },
  { value: 'BT', label: 'Bhutan', flag: 'https://flagcdn.com/w40/bt.png' },
  { value: 'BO', label: 'Bolivia', flag: 'https://flagcdn.com/w40/bo.png' },
  { value: 'BA', label: 'Bosnia & Herzegovina', flag: 'https://flagcdn.com/w40/ba.png' },
  { value: 'BW', label: 'Botswana', flag: 'https://flagcdn.com/w40/bw.png' },
  { value: 'BR', label: 'Brazil', flag: 'https://flagcdn.com/w40/br.png' },
  { value: 'IO', label: 'British Indian Ocean Territory', flag: 'https://flagcdn.com/w40/io.png' },
  { value: 'VG', label: 'British Virgin Islands', flag: 'https://flagcdn.com/w40/vg.png' },
  { value: 'BN', label: 'Brunei', flag: 'https://flagcdn.com/w40/bn.png' },
  { value: 'BG', label: 'Bulgaria', flag: 'https://flagcdn.com/w40/bg.png' },
  { value: 'BF', label: 'Burkina Faso', flag: 'https://flagcdn.com/w40/bf.png' },
  { value: 'BI', label: 'Burundi', flag: 'https://flagcdn.com/w40/bi.png' },
  { value: 'KH', label: 'Cambodia', flag: 'https://flagcdn.com/w40/kh.png' },
  { value: 'CM', label: 'Cameroon', flag: 'https://flagcdn.com/w40/cm.png' },
  { value: 'CA', label: 'Canada', flag: 'https://flagcdn.com/w40/ca.png' },
  { value: 'CV', label: 'Cape Verde', flag: 'https://flagcdn.com/w40/cv.png' },
  { value: 'BQ', label: 'Caribbean Netherlands', flag: 'https://flagcdn.com/w40/bq.png' },
  { value: 'KY', label: 'Cayman Islands', flag: 'https://flagcdn.com/w40/ky.png' },
  { value: 'CF', label: 'Central African Republic', flag: 'https://flagcdn.com/w40/cf.png' },
  { value: 'TD', label: 'Chad', flag: 'https://flagcdn.com/w40/td.png' },
  { value: 'CL', label: 'Chile', flag: 'https://flagcdn.com/w40/cl.png' },
  { value: 'CN', label: 'China', flag: 'https://flagcdn.com/w40/cn.png' },
  { value: 'CX', label: 'Christmas Island', flag: 'https://flagcdn.com/w40/cx.png' },
  { value: 'CC', label: 'Cocos (Keeling) Islands', flag: 'https://flagcdn.com/w40/cc.png' },
  { value: 'CO', label: 'Colombia', flag: 'https://flagcdn.com/w40/co.png' },
  { value: 'KM', label: 'Comoros', flag: 'https://flagcdn.com/w40/km.png' },
  { value: 'CG', label: 'Congo - Brazzaville', flag: 'https://flagcdn.com/w40/cg.png' },
  { value: 'CD', label: 'Congo - Kinshasa', flag: 'https://flagcdn.com/w40/cd.png' },
  { value: 'CK', label: 'Cook Islands', flag: 'https://flagcdn.com/w40/ck.png' },
  { value: 'CR', label: 'Costa Rica', flag: 'https://flagcdn.com/w40/cr.png' },
  { value: 'CI', label: 'Côte d’Ivoire', flag: 'https://flagcdn.com/w40/ci.png' },
  { value: 'HR', label: 'Croatia', flag: 'https://flagcdn.com/w40/hr.png' },
  { value: 'CU', label: 'Cuba', flag: 'https://flagcdn.com/w40/cu.png' },
  { value: 'CW', label: 'Curaçao', flag: 'https://flagcdn.com/w40/cw.png' },
  { value: 'CY', label: 'Cyprus', flag: 'https://flagcdn.com/w40/cy.png' },
  { value: 'CZ', label: 'Czechia', flag: 'https://flagcdn.com/w40/cz.png' },
  { value: 'DK', label: 'Denmark', flag: 'https://flagcdn.com/w40/dk.png' },
  { value: 'DJ', label: 'Djibouti', flag: 'https://flagcdn.com/w40/dj.png' },
  { value: 'DM', label: 'Dominica', flag: 'https://flagcdn.com/w40/dm.png' },
  { value: 'DO', label: 'Dominican Republic', flag: 'https://flagcdn.com/w40/do.png' },
  { value: 'EC', label: 'Ecuador', flag: 'https://flagcdn.com/w40/ec.png' },
  { value: 'EG', label: 'Egypt', flag: 'https://flagcdn.com/w40/eg.png' },
  { value: 'SV', label: 'El Salvador', flag: 'https://flagcdn.com/w40/sv.png' },
  { value: 'GQ', label: 'Equatorial Guinea', flag: 'https://flagcdn.com/w40/gq.png' },
  { value: 'ER', label: 'Eritrea', flag: 'https://flagcdn.com/w40/er.png' },
  { value: 'EE', label: 'Estonia', flag: 'https://flagcdn.com/w40/ee.png' },
  { value: 'SZ', label: 'Eswatini', flag: 'https://flagcdn.com/w40/sz.png' },
  { value: 'ET', label: 'Ethiopia', flag: 'https://flagcdn.com/w40/et.png' },
  { value: 'FK', label: 'Falkland Islands', flag: 'https://flagcdn.com/w40/fk.png' },
  { value: 'FO', label: 'Faroe Islands', flag: 'https://flagcdn.com/w40/fo.png' },
  { value: 'FJ', label: 'Fiji', flag: 'https://flagcdn.com/w40/fj.png' },
  { value: 'FI', label: 'Finland', flag: 'https://flagcdn.com/w40/fi.png' },
  { value: 'FR', label: 'France', flag: 'https://flagcdn.com/w40/fr.png' },
  { value: 'GF', label: 'French Guiana', flag: 'https://flagcdn.com/w40/gf.png' },
  { value: 'PF', label: 'French Polynesia', flag: 'https://flagcdn.com/w40/pf.png' },
  { value: 'TF', label: 'French Southern Territories', flag: 'https://flagcdn.com/w40/tf.png' },
  { value: 'GA', label: 'Gabon', flag: 'https://flagcdn.com/w40/ga.png' },
  { value: 'GM', label: 'Gambia', flag: 'https://flagcdn.com/w40/gm.png' },
  { value: 'GE', label: 'Georgia', flag: 'https://flagcdn.com/w40/ge.png' },
  { value: 'DE', label: 'Germany', flag: 'https://flagcdn.com/w40/de.png' },
  { value: 'GH', label: 'Ghana', flag: 'https://flagcdn.com/w40/gh.png' },
  { value: 'GI', label: 'Gibraltar', flag: 'https://flagcdn.com/w40/gi.png' },
  { value: 'GR', label: 'Greece', flag: 'https://flagcdn.com/w40/gr.png' },
  { value: 'GL', label: 'Greenland', flag: 'https://flagcdn.com/w40/gl.png' },
  { value: 'GD', label: 'Grenada', flag: 'https://flagcdn.com/w40/gd.png' },
  { value: 'GP', label: 'Guadeloupe', flag: 'https://flagcdn.com/w40/gp.png' },
  { value: 'GU', label: 'Guam', flag: 'https://flagcdn.com/w40/gu.png' },
  { value: 'GT', label: 'Guatemala', flag: 'https://flagcdn.com/w40/gt.png' },
  { value: 'GG', label: 'Guernsey', flag: 'https://flagcdn.com/w40/gg.png' },
  { value: 'GN', label: 'Guinea', flag: 'https://flagcdn.com/w40/gn.png' },
  { value: 'GW', label: 'Guinea-Bissau', flag: 'https://flagcdn.com/w40/gw.png' },
  { value: 'GY', label: 'Guyana', flag: 'https://flagcdn.com/w40/gy.png' },
  { value: 'HT', label: 'Haiti', flag: 'https://flagcdn.com/w40/ht.png' },
  { value: 'HN', label: 'Honduras', flag: 'https://flagcdn.com/w40/hn.png' },
  { value: 'HK', label: 'Hong Kong SAR China', flag: 'https://flagcdn.com/w40/hk.png' },
  { value: 'HU', label: 'Hungary', flag: 'https://flagcdn.com/w40/hu.png' },
  { value: 'IS', label: 'Iceland', flag: 'https://flagcdn.com/w40/is.png' },
  { value: 'IN', label: 'India', flag: 'https://flagcdn.com/w40/in.png' },
  { value: 'ID', label: 'Indonesia', flag: 'https://flagcdn.com/w40/id.png' },
  { value: 'IR', label: 'Iran', flag: 'https://flagcdn.com/w40/ir.png' },
  { value: 'IQ', label: 'Iraq', flag: 'https://flagcdn.com/w40/iq.png' },
  { value: 'IE', label: 'Ireland', flag: 'https://flagcdn.com/w40/ie.png' },
  { value: 'IM', label: 'Isle of Man', flag: 'https://flagcdn.com/w40/im.png' },
  { value: 'IL', label: 'Israel', flag: 'https://flagcdn.com/w40/il.png' },
  { value: 'IT', label: 'Italy', flag: 'https://flagcdn.com/w40/it.png' },
  { value: 'JM', label: 'Jamaica', flag: 'https://flagcdn.com/w40/jm.png' },
  { value: 'JP', label: 'Japan', flag: 'https://flagcdn.com/w40/jp.png' },
  { value: 'JE', label: 'Jersey', flag: 'https://flagcdn.com/w40/je.png' },
  { value: 'JO', label: 'Jordan', flag: 'https://flagcdn.com/w40/jo.png' },
  { value: 'KZ', label: 'Kazakhstan', flag: 'https://flagcdn.com/w40/kz.png' },
  { value: 'KE', label: 'Kenya', flag: 'https://flagcdn.com/w40/ke.png' },
  { value: 'KI', label: 'Kiribati', flag: 'https://flagcdn.com/w40/ki.png' },
  { value: 'XK', label: 'Kosovo', flag: 'https://flagcdn.com/w40/xk.png' },
  { value: 'KW', label: 'Kuwait', flag: 'https://flagcdn.com/w40/kw.png' },
  { value: 'KG', label: 'Kyrgyzstan', flag: 'https://flagcdn.com/w40/kg.png' },
  { value: 'LA', label: 'Laos', flag: 'https://flagcdn.com/w40/la.png' },
  { value: 'LV', label: 'Latvia', flag: 'https://flagcdn.com/w40/lv.png' },
  { value: 'LB', label: 'Lebanon', flag: 'https://flagcdn.com/w40/lb.png' },
  { value: 'LS', label: 'Lesotho', flag: 'https://flagcdn.com/w40/ls.png' },
  { value: 'LR', label: 'Liberia', flag: 'https://flagcdn.com/w40/lr.png' },
  { value: 'LY', label: 'Libya', flag: 'https://flagcdn.com/w40/ly.png' },
  { value: 'LI', label: 'Liechtenstein', flag: 'https://flagcdn.com/w40/li.png' },
  { value: 'LT', label: 'Lithuania', flag: 'https://flagcdn.com/w40/lt.png' },
  { value: 'LU', label: 'Luxembourg', flag: 'https://flagcdn.com/w40/lu.png' },
  { value: 'MO', label: 'Macao SAR China', flag: 'https://flagcdn.com/w40/mo.png' },
  { value: 'MG', label: 'Madagascar', flag: 'https://flagcdn.com/w40/mg.png' },
  { value: 'MW', label: 'Malawi', flag: 'https://flagcdn.com/w40/mw.png' },
  { value: 'MY', label: 'Malaysia', flag: 'https://flagcdn.com/w40/my.png' },
  { value: 'MV', label: 'Maldives', flag: 'https://flagcdn.com/w40/mv.png' },
  { value: 'ML', label: 'Mali', flag: 'https://flagcdn.com/w40/ml.png' },
  { value: 'MT', label: 'Malta', flag: 'https://flagcdn.com/w40/mt.png' },
  { value: 'MH', label: 'Marshall Islands', flag: 'https://flagcdn.com/w40/mh.png' },
  { value: 'MQ', label: 'Martinique', flag: 'https://flagcdn.com/w40/mq.png' },
  { value: 'MR', label: 'Mauritania', flag: 'https://flagcdn.com/w40/mr.png' },
  { value: 'MU', label: 'Mauritius', flag: 'https://flagcdn.com/w40/mu.png' },
  { value: 'YT', label: 'Mayotte', flag: 'https://flagcdn.com/w40/yt.png' },
  { value: 'MX', label: 'Mexico', flag: 'https://flagcdn.com/w40/mx.png' },
  { value: 'FM', label: 'Micronesia', flag: 'https://flagcdn.com/w40/fm.png' },
  { value: 'MD', label: 'Moldova', flag: 'https://flagcdn.com/w40/md.png' },
  { value: 'MC', label: 'Monaco', flag: 'https://flagcdn.com/w40/mc.png' },
  { value: 'MN', label: 'Mongolia', flag: 'https://flagcdn.com/w40/mn.png' },
  { value: 'ME', label: 'Montenegro', flag: 'https://flagcdn.com/w40/me.png' },
  { value: 'MS', label: 'Montserrat', flag: 'https://flagcdn.com/w40/ms.png' },
  { value: 'MA', label: 'Morocco', flag: 'https://flagcdn.com/w40/ma.png' },
  { value: 'MZ', label: 'Mozambique', flag: 'https://flagcdn.com/w40/mz.png' },
  { value: 'MM', label: 'Myanmar (Burma)', flag: 'https://flagcdn.com/w40/mm.png' },
  { value: 'NA', label: 'Namibia', flag: 'https://flagcdn.com/w40/na.png' },
  { value: 'NR', label: 'Nauru', flag: 'https://flagcdn.com/w40/nr.png' },
  { value: 'NP', label: 'Nepal', flag: 'https://flagcdn.com/w40/np.png' },
  { value: 'NL', label: 'Netherlands', flag: 'https://flagcdn.com/w40/nl.png' },
  { value: 'NC', label: 'New Caledonia', flag: 'https://flagcdn.com/w40/nc.png' },
  { value: 'NZ', label: 'New Zealand', flag: 'https://flagcdn.com/w40/nz.png' },
  { value: 'NI', label: 'Nicaragua', flag: 'https://flagcdn.com/w40/ni.png' },
  { value: 'NE', label: 'Niger', flag: 'https://flagcdn.com/w40/ne.png' },
  { value: 'NG', label: 'Nigeria', flag: 'https://flagcdn.com/w40/ng.png' },
  { value: 'NU', label: 'Niue', flag: 'https://flagcdn.com/w40/nu.png' },
  { value: 'NF', label: 'Norfolk Island', flag: 'https://flagcdn.com/w40/nf.png' },
  { value: 'KP', label: 'North Korea', flag: 'https://flagcdn.com/w40/kp.png' },
  { value: 'MK', label: 'North Macedonia', flag: 'https://flagcdn.com/w40/mk.png' },
  { value: 'MP', label: 'Northern Mariana Islands', flag: 'https://flagcdn.com/w40/mp.png' },
  { value: 'NO', label: 'Norway', flag: 'https://flagcdn.com/w40/no.png' },
  { value: 'OM', label: 'Oman', flag: 'https://flagcdn.com/w40/om.png' },
  { value: 'PK', label: 'Pakistan', flag: 'https://flagcdn.com/w40/pk.png' },
  { value: 'PW', label: 'Palau', flag: 'https://flagcdn.com/w40/pw.png' },
  { value: 'PS', label: 'Palestinian Territories', flag: 'https://flagcdn.com/w40/ps.png' },
  { value: 'PA', label: 'Panama', flag: 'https://flagcdn.com/w40/pa.png' },
  { value: 'PG', label: 'Papua New Guinea', flag: 'https://flagcdn.com/w40/pg.png' },
  { value: 'PY', label: 'Paraguay', flag: 'https://flagcdn.com/w40/py.png' },
  { value: 'PE', label: 'Peru', flag: 'https://flagcdn.com/w40/pe.png' },
  { value: 'PH', label: 'Philippines', flag: 'https://flagcdn.com/w40/ph.png' },
  { value: 'PN', label: 'Pitcairn Islands', flag: 'https://flagcdn.com/w40/pn.png' },
  { value: 'PL', label: 'Poland', flag: 'https://flagcdn.com/w40/pl.png' },
  { value: 'PT', label: 'Portugal', flag: 'https://flagcdn.com/w40/pt.png' },
  { value: 'PR', label: 'Puerto Rico', flag: 'https://flagcdn.com/w40/pr.png' },
  { value: 'QA', label: 'Qatar', flag: 'https://flagcdn.com/w40/qa.png' },
  { value: 'RE', label: 'Réunion', flag: 'https://flagcdn.com/w40/re.png' },
  { value: 'RO', label: 'Romania', flag: 'https://flagcdn.com/w40/ro.png' },
  { value: 'RU', label: 'Russia', flag: 'https://flagcdn.com/w40/ru.png' },
  { value: 'RW', label: 'Rwanda', flag: 'https://flagcdn.com/w40/rw.png' },
  { value: 'WS', label: 'Samoa', flag: 'https://flagcdn.com/w40/ws.png' },
  { value: 'SM', label: 'San Marino', flag: 'https://flagcdn.com/w40/sm.png' },
  { value: 'ST', label: 'São Tomé & Príncipe', flag: 'https://flagcdn.com/w40/st.png' },
  { value: 'SA', label: 'Saudi Arabia', flag: 'https://flagcdn.com/w40/sa.png' },
  { value: 'SN', label: 'Senegal', flag: 'https://flagcdn.com/w40/sn.png' },
  { value: 'RS', label: 'Serbia', flag: 'https://flagcdn.com/w40/rs.png' },
  { value: 'SC', label: 'Seychelles', flag: 'https://flagcdn.com/w40/sc.png' },
  { value: 'SL', label: 'Sierra Leone', flag: 'https://flagcdn.com/w40/sl.png' },
  { value: 'SG', label: 'Singapore', flag: 'https://flagcdn.com/w40/sg.png' },
  { value: 'SX', label: 'Sint Maarten', flag: 'https://flagcdn.com/w40/sx.png' },
  { value: 'SK', label: 'Slovakia', flag: 'https://flagcdn.com/w40/sk.png' },
  { value: 'SI', label: 'Slovenia', flag: 'https://flagcdn.com/w40/si.png' },
  { value: 'SB', label: 'Solomon Islands', flag: 'https://flagcdn.com/w40/sb.png' },
  { value: 'SO', label: 'Somalia', flag: 'https://flagcdn.com/w40/so.png' },
  { value: 'ZA', label: 'South Africa', flag: 'https://flagcdn.com/w40/za.png' },
  { value: 'KR', label: 'South Korea', flag: 'https://flagcdn.com/w40/kr.png' },
  { value: 'SS', label: 'South Sudan', flag: 'https://flagcdn.com/w40/ss.png' },
  { value: 'ES', label: 'Spain', flag: 'https://flagcdn.com/w40/es.png' },
  { value: 'LK', label: 'Sri Lanka', flag: 'https://flagcdn.com/w40/lk.png' },
  { value: 'BL', label: 'St. Barthélemy', flag: 'https://flagcdn.com/w40/bl.png' },
  { value: 'SH', label: 'St. Helena', flag: 'https://flagcdn.com/w40/sh.png' },
  { value: 'KN', label: 'St. Kitts & Nevis', flag: 'https://flagcdn.com/w40/kn.png' },
  { value: 'LC', label: 'St. Lucia', flag: 'https://flagcdn.com/w40/lc.png' },
  { value: 'MF', label: 'St. Martin', flag: 'https://flagcdn.com/w40/mf.png' },
  { value: 'PM', label: 'St. Pierre & Miquelon', flag: 'https://flagcdn.com/w40/pm.png' },
  { value: 'VC', label: 'St. Vincent & Grenadines', flag: 'https://flagcdn.com/w40/vc.png' },
  { value: 'SD', label: 'Sudan', flag: 'https://flagcdn.com/w40/sd.png' },
  { value: 'SR', label: 'Suriname', flag: 'https://flagcdn.com/w40/sr.png' },
  { value: 'SJ', label: 'Svalbard & Jan Mayen', flag: 'https://flagcdn.com/w40/sj.png' },
  { value: 'SE', label: 'Sweden', flag: 'https://flagcdn.com/w40/se.png' },
  { value: 'CH', label: 'Switzerland', flag: 'https://flagcdn.com/w40/ch.png' },
  { value: 'SY', label: 'Syria', flag: 'https://flagcdn.com/w40/sy.png' },
  { value: 'TW', label: 'Taiwan', flag: 'https://flagcdn.com/w40/tw.png' },
  { value: 'TJ', label: 'Tajikistan', flag: 'https://flagcdn.com/w40/tj.png' },
  { value: 'TZ', label: 'Tanzania', flag: 'https://flagcdn.com/w40/tz.png' },
  { value: 'TH', label: 'Thailand', flag: 'https://flagcdn.com/w40/th.png' },
  { value: 'TL', label: 'Timor-Leste', flag: 'https://flagcdn.com/w40/tl.png' },
  { value: 'TG', label: 'Togo', flag: 'https://flagcdn.com/w40/tg.png' },
  { value: 'TK', label: 'Tokelau', flag: 'https://flagcdn.com/w40/tk.png' },
  { value: 'TO', label: 'Tonga', flag: 'https://flagcdn.com/w40/to.png' },
  { value: 'TT', label: 'Trinidad & Tobago', flag: 'https://flagcdn.com/w40/tt.png' },
  { value: 'TN', label: 'Tunisia', flag: 'https://flagcdn.com/w40/tn.png' },
  { value: 'TR', label: 'Turkey', flag: 'https://flagcdn.com/w40/tr.png' },
  { value: 'TM', label: 'Turkmenistan', flag: 'https://flagcdn.com/w40/tm.png' },
  { value: 'TC', label: 'Turks & Caicos Islands', flag: 'https://flagcdn.com/w40/tc.png' },
  { value: 'TV', label: 'Tuvalu', flag: 'https://flagcdn.com/w40/tv.png' },
  { value: 'UG', label: 'Uganda', flag: 'https://flagcdn.com/w40/ug.png' },
  { value: 'UA', label: 'Ukraine', flag: 'https://flagcdn.com/w40/ua.png' },
  { value: 'AE', label: 'United Arab Emirates', flag: 'https://flagcdn.com/w40/ae.png' },
  { value: 'GB', label: 'United Kingdom', flag: 'https://flagcdn.com/w40/gb.png' },
  { value: 'US', label: 'United States', flag: 'https://flagcdn.com/w40/us.png' },
  { value: 'UY', label: 'Uruguay', flag: 'https://flagcdn.com/w40/uy.png' },
  { value: 'UZ', label: 'Uzbekistan', flag: 'https://flagcdn.com/w40/uz.png' },
  { value: 'VU', label: 'Vanuatu', flag: 'https://flagcdn.com/w40/vu.png' },
  { value: 'VA', label: 'Vatican City', flag: 'https://flagcdn.com/w40/va.png' },
  { value: 'VE', label: 'Venezuela', flag: 'https://flagcdn.com/w40/ve.png' },
  { value: 'VN', label: 'Vietnam', flag: 'https://flagcdn.com/w40/vn.png' },
  { value: 'WF', label: 'Wallis & Futuna', flag: 'https://flagcdn.com/w40/wf.png' },
  { value: 'EH', label: 'Western Sahara', flag: 'https://flagcdn.com/w40/eh.png' },
  { value: 'YE', label: 'Yemen', flag: 'https://flagcdn.com/w40/ye.png' },
  { value: 'ZM', label: 'Zambia', flag: 'https://flagcdn.com/w40/zm.png' },
  { value: 'ZW', label: 'Zimbabwe', flag: 'https://flagcdn.com/w40/zw.png' }
]
