import { useState } from 'react';
import { X } from 'lucide-react';

export default function HelpModal({ onClose }) {
  const tabs = {
    efi: { label: 'EFI', title: 'Evaluación de factores internos', formula: 'Puntaje EFI = suma de (peso × calificación)', scale: 'Peso: 0 a 1 · Calificación: 1 a 4 · Referencia orientativa: 2.50', body: 'EFI resume fortalezas y debilidades. El peso representa importancia relativa y la calificación expresa la posición o respuesta interna observada.', warning: 'Los pesos deben sumar 1.00 y cada factor debe conservar nombre, calificación y evidencia.' },
    efe: { label: 'EFE', title: 'Evaluación de factores externos', formula: 'Puntaje EFE = suma de (peso × calificación)', scale: 'Peso: 0 a 1 · Calificación: 1 a 4 · Referencia orientativa: 2.50', body: 'EFE ordena oportunidades y amenazas según su importancia y la respuesta de la organización ante el entorno.', warning: 'Una calificación alta no significa que el entorno sea favorable: indica una respuesta más eficaz ante ese factor.' },
    dafo: { label: 'DAFO', title: 'Cruces, fuerza y orientación', formula: 'Contribución = peso interno × peso externo × (fuerza / 3)', scale: 'Fuerza: pendiente · 0 sin relación · 1 débil · 2 moderada · 3 fuerte', body: 'La matriz exploratoria muestra potencial. La orientación operativa sólo se considera concluyente cuando existen relaciones evaluadas, cobertura suficiente y diferencia frente al segundo cuadrante.', warning: 'No complete una relación por intuición: registre justificación, evidencia, evaluador y fecha.' },
    came: { label: 'CAME', title: 'De factores a acciones', formula: 'Prioridad = suma de (peso del criterio × valor del criterio / 5)', scale: 'Criterios: impacto · urgencia · severidad · alineación · factibilidad', body: 'CAME traduce debilidades en acciones para corregir, amenazas para afrontar, fortalezas para mantener y oportunidades para explotar.', warning: 'Los cinco pesos deben sumar 1.00; cada ficha necesita responsable, fechas, indicador, línea base, meta y estado.' },
    example: { label: 'Ejemplo', title: 'Lectura de un caso completo', formula: 'D-08 + O-01 · fuerza 3 · estrategia EST-DO-01 · acción ACC-D-08', scale: 'Evidencia simulada · no sustituye validación institucional', body: 'Una debilidad de integración puede relacionarse con una oportunidad de transformación digital. La relación alimenta la orientación DO, la alternativa se compara en QSPM y la acción CAME documenta cómo medir el avance.', warning: 'El caso demostrativo sirve para recorrer el flujo; reemplácelo por fuentes y responsables reales antes de validar o exportar.' }
  };
  const [activeTab, setActiveTab] = useState('efi');
  const current = tabs[activeTab];
  return <div className="modal-backdrop"><dialog open className="help-modal" aria-labelledby="help-title"><button className="modal-close" type="button" onClick={onClose} aria-label="Cerrar guía"><X size={17} /></button><p className="eyebrow">Guía metodológica</p><h2 id="help-title">Cómo leer la mesa</h2><div className="help-tabs" role="tablist">{Object.entries(tabs).map(([id, tab]) => <button className={`help-tab ${activeTab === id ? 'is-active' : ''}`} type="button" role="tab" aria-selected={activeTab === id} key={id} onClick={() => setActiveTab(id)}>{tab.label}</button>)}</div><article className="help-content"><p className="eyebrow">{current.label}</p><h3>{current.title}</h3><p>{current.body}</p><div className="help-formula"><span>Fórmula / escala</span><strong>{current.formula}</strong><small>{current.scale}</small></div><div className="help-warning"><strong>Advertencia</strong><p>{current.warning}</p></div></article><div className="help-glossary"><strong>Glosario rápido</strong><span><code>AS</code> atractivo relativo · <code>TAS</code> atractivo ponderado · <code>EFI/EFE</code> puntajes agregados · <code>cobertura</code> proporción de pares evaluados.</span></div><button className="button button-primary" type="button" onClick={onClose}>Cerrar guía</button></dialog></div>;
}
